version: '3'
services:
  ftps:
    image: ertuil/wickftps:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
     - "20:20"
     - "21:21"
     - "2222:22"
     - "3000-3010:3000-3010"
     - "8080:80"
    environment:
     USER_USERNAME: username
     USER_PASSWORD: password
     PASV_ADDRESS: 127.0.0.1
     PASV_MAX_PORT: 3010
     PASV_MIN_PORT: 3000
     FTP_SSL: "true"
     ENABLE_SSH: "true"
    volumes:
      - ./data:/app
    restart: always